language: python
python: '3.5'
install:
  - pip install --upgrade pip && pip install six && pip install -r requirements.txt

script: python runWS.py

after_success:
  - coveralls

branches:
  only:
  - master
