language: python
python:
  - '2.7'
  - '3.5'
install:
  - pip install --upgrade pip && pip install six && pip install -r requirements.txt

script:
  python mtblsWSclient.py

after_success:
  - coveralls

branches:
  only:
  - master

deploy:
  skip_cleanup: true
