version: '3'

services:
  webservice:
    image: mtblsws-py
    build: .
    # Mounted paths must be same paths defined in config files
    volumes:
      - .:/app-root
      - <some-folder>:/shared-folders/queue
      - <some-folder>:/shared-folders/studies
      - <some-folder>:/shared-folders/ftp
      - <some-folder>:/shared-folders/chebi
      - <some-folder>:/shared-folders/isatab
      - <some-folder>:/shared-folders/validation
        -e INSTANCE_DIR="$(pwd)/docker-instance"
    ports:
    - "5005:5000"
    networks:
    - host
    environment:
      - INSTANCE_DIR="$(pwd)/docker-instance"

networks:
    ws_network:
