flask:
    ENV: Development
    TESTING: True
    DEBUG: True
    SECRET_KEY: <secret_file:flask_secret_key>
server:
    service:
        port: 5001
        app_host_url: https://wwwdev.ebi.ac.uk
        ws_app_base_link: https://wwwdev.ebi.ac.uk/metabolights
        mtbls_ws_host: http://vm_internal_name
        resources_path: /metabolights/ws
        cors_hosts: "*"
        cors_resources_path: /metabolights/ws/*
        api_doc: /metabolights/ws/api/spec
    log:
        log_path: ./logs
        log_config_file_path: ''
        log_headers: True
        log_body: False
        log_json: False
    temp_directory_path: /tmp

database:
    connection: 
        host: dbhost
        port: 5432
        user: dbuser
        password: <secret_file:database_password>
        database: db
    configuration:
        conn_pool_min: 1
        conn_pool_max: 3
elasticsearch:
    connection: 
        host: localhost
        port: 9200
        username: ''
        password: ''
        use_tls: False
    configuration:
        elasticsearch_all_mappings_json: ./resources/es_all_mappings.json
        elasticsearch_study_mappings_json:  ./resources/es_study_mappings.json
        elasticsearch_compound_mappings_json:  ./resources/es_compound_mappings.json
email:
    email_service:
        connection: 
            host: localhost
            port: 25
            username: ''
            password: <secret_file:email_service_password>
            use_tls: False
            use_ssl: False
        configuration:
            no_reply_email_address: test@user.com
            curation_email_address: test@user.com
            technical_issue_recipient_email_address: test@user.com
            hpc_cluster_job_track_email_address: test@user.com
    template_email_configuration:
        # Help document URL to upload data to MetaboLigts private FTP server
        ftp_upload_help_doc_url: https://docs.google.com/document/d/15rSS6Mrj2Aj_uMyh4-3n8RJzAdWi1uoHsaKkxqPyC4I            
auth:
    configuration:
        access_token_hash_algorithm: HS256
        access_token_expires_delta: 300
        access_token_allowed_audience: Metabolights Editor
        access_token_issuer_name: Metabolights PythonWS
        application_secret_key: <secret_file:application_secret_key>
        one_time_token_expires_in_seconds: 300
        admin_jwt_token_expires_in_mins: 480
    service_account:
        email: test@user.com
        api_token: <secret_file:service_account_api_token>
ftp_server:
    private:
        connection:
            host: ft-server-host
            username: ftp_user
            password: <secret_file:private_ftp_server_password>
        configuration:
            mount_type: remote_worker
    public:
        configuration:
            mount_type: remote_worker
jira:
    connection:
        username: jira_user
        password: <secret_file:jira_password>
twitter:
    connection: <secret_file:twitter_credentials.json>
metaspace:
    connection: <secret_file:metaspace_credentials.json>
    configuration: 
        metaspace_database: HMDB-v4
        metaspace_fdr: "0.1"
chebi:
    service:
        connection:
            chebi_ws_wsdl: https://www.ebi.ac.uk/webservices/chebi/2.0/webservice?wsdl
            chebi_ws_wsdl_service: ChebiWebServiceService
            chebi_ws_wsdl_service_port: ChebiWebServicePort
        configuration:
            chebi_ws_service_binding_log_level: ERROR
            chebi_ws_strict: False
            chebi_ws_xml_huge_tree: True            
    pipeline:
        curated_metabolite_list_file_location: /file/path/test/MasterList.txt
        chebi_upload_script:/file/path/dev/studies/stage/private/chebi/metabolights.sh
        chebi_pipeline_url: http://internal-server:5000/metabolights/ws/ebi-internal/
        chebi_pipeline_annotation_folder: chebi_pipeline_annotations
        obo_file:/file/path/chebi/ontology/chebi_lite.obo
        chebi_url_wait: 300
        removed_hs_mol_count: 500
        classyfire_mapping:/file/path/metabolights/submissionTool/ClassyFire_Mapping.tsv
        search_services:
            classyfire_url: http://classyfire_url
            opsin_url: https://opsin.ch.cam.ac.uk/opsin/
            chemspider_url: http://parts.chemspider.com/JSON.ashx?op=
            chem_plus_url: https://chem.nlm.nih.gov/api/data/inchikey/equals/INCHI_KEY?data=summary
            unichem_url: https://www.ebi.ac.uk/unichem/rest/inchikey/INCHI_KEY
            dime_url: https://dimedb.ibers.aber.ac.uk/api/metabolites?where={%22_id%22%20:%20%22INCHI_KEY%22}&projection={%22External%20Sources%22%20:%201}           
google:
    connection:
        google_sheet_api: <secret_file:google_sheet_api_credentials.json>
        google_calender_api: <secret_file:google_calendar_api_credentials.json>
    services:
        google_calendar_id: <secret_file:google_calendar_id>
        google_analytics_tracking_id: <secret_file:google_analytics_tracking_id>
        google_mariana_drive_id: <secret_file:google_mariana_drive_id>
    sheets:
        zooma_sheet: https://docs.google.com/spreadsheets/d/zooma_sheet
        europe_pmc_report: https://docs.google.com/spreadsheets/d/europe_pmc_report-E
        mtbls_statistics: https://docs.google.com/spreadsheets/d/mtbls_statistics
        lc_ms_statistics: https://docs.google.com/spreadsheets/d/lc_ms_statistics/edit#gid=805314595
        mtbls_curation_log: https://docs.google.com/spreadsheets/d/mtbls_curation_log
bioportal:
    api_token: <secret_file:bioportal_api_token>
    url: http://data.bioontology.org
redis_cache:
    connection:
        redis_host: redis
        redis_password: <secret_file:redis_cache_password>
        redis_port: 9111
        redis_db: 10
    configuration:
        banner_message_key: metabolights:test-banner:message
        species_tree_cache_key: metabolights:test-species:tree
celery:
    broker:
        redis_host: redis
        redis_password: <secret_file:redis_cache_password>
        redis_port: 9111
        redis_db: 10
    configuration:
        celery_result_expires: 300
    periodic_task_configuration:
        integration_test_period_in_seconds: 60
        es_compound_sync_task_period_in_secs: 600
        es_study_sync_task_period_in_secs: 600
        worker_heath_check_period_in_seconds: 30
report:
    mariana_report_folder_name : mariana
    report_base_folder_name: base
    report_global_folder_name: global
hpc_cluster:
    datamover:
        connection:
            host: hpc_login
            username: user
        queue_name: datamover
        cluster_private_ftp_user_home_path: /private/ftp/user
        mounted_paths:
            cluster_study_metadata_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/metadata-files
            cluster_study_internal_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/internal-files
            cluster_study_audit_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/audit-files
            cluster_study_readonly_files_root_path: /path/to/data/services/metabolomics/dev/studies/data-files
            cluster_study_readonly_metadata_files_root_path: /path/to/data/services/metabolomics/dev/studies/metadata-files
            cluster_study_readonly_public_metadata_versions_root_path: /path/to/data/services/metabolomics/dev/studies/public-metadata-versions
            cluster_study_readonly_audit_files_root_path: /path/to/data/services/metabolomics/dev/studies/audit-files
            cluster_study_readonly_integrity_check_files_root_path: /path/to/data/services/metabolomics/dev/studies/integrity-check-files
            cluster_readonly_storage_recycle_bin_root_path: /path/to/data/services/metabolomics/dev/studies/deleted-files
            cluster_rw_storage_recycle_bin_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/deleted-files
            
            cluster_private_ftp_root_path: /private/ftp/user/dev
            cluster_private_ftp_recycle_bin_root_path: /private/ftp/user/dev/.deleted-files
            cluster_public_ftp_root_path: /public/ftp/path//databases/metabolights/.test/.deleted-files
            cluster_public_ftp_recycle_bin_root_path: /public/ftp/path//databases/metabolights/.test/.deleted-files 
            cluster_reports_root_path: /path/to/data/rw/metabolomics/dev/reports
            cluster_compounds_root_path: /path/to/data/prod/reference
        worker:
            number_of_datamover_workers: 1
            datamover_worker_maximum_uptime_in_seconds:  259200
            datamover_worker_submission_script_template_name: run_singularity.sh.j2
            worker_deployment_root_path: /hpc/data/path
            broker_queue_names: datamover-tasks
            singularity_image: /hpc/data/path/metablsws-py_test-latest.sif
            singularity_docker_username: ozgur
            singularity_docker_password: <secret_file:singularity_docker_password>
            user_home_binding_source_path: /homes/tc_cm01
            user_home_binding_target_path: /home/tc_cm01
            logs_path: /hpc/data/path/logs
            config_file_path: /hpc/data/path/config.yaml
            secrets_path: /hpc/data/path/.secrets
            shared_paths:
            - /path/to/data/prod/studies/stage/private
            - /path/to/data/services/metabolomics
            - /path/to/data/rw/metabolomics
            - /private/ftp/user/dev
            - /public/ftp/path//databases/metabolights/studies/public
            - /path/to/data/rw/metabolomics/dev/compounds
    compute:
        connection:
            host: hpc_login
            username: compute_user
        standard_queue: standard
        long_process_queue: long
        default_queue: default
    ssh_command: /usr/bin/ssh
    configuration:
        job_project_name: metabolights-ws-test
        task_get_timeout_in_seconds: 10
        job_status_read_timeout: 10
        job_submit_command: bsub
        job_running_command: bjobs
        job_kill_command: bkill
        job_track_log_location: /hpc/data/path/logs/jobs
        maximum_shutdown_signal_per_time: 1
        number_of_additional_localhost_workers: 0
        number_of_remote_vm_workers: 0
        vm_worker_hostnames: remote_vm_name
        start_vm_worker_script_template_name: start_vm_worker_template.sh.j2
        remote_vm_deployment_path: /path/to/data/rw/metabolomics/development/ozgur/MtblsWS-Py
        remote_vm_conda_environment: python38-MtblsWS
        localhost_conda_environment: python38-MtblsWS
        fella_pathway_script_path: /invalid

study:
    mounted_paths:
        study_metadata_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/metadata-files
        study_internal_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/internal-files
        study_audit_files_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/audit-files
        study_readonly_files_root_path: /path/to/data/services/metabolomics/dev/studies/data-files
        study_readonly_metadata_files_root_path: /path/to/data/services/metabolomics/dev/studies/metadata-files
        study_readonly_audit_files_root_path: /path/to/data/services/metabolomics/dev/studies/audit-files
        study_readonly_public_metadata_versions_root_path: /path/to/data/services/metabolomics/dev/studies/public-metadata-versions
        study_readonly_integrity_check_files_root_path: /path/to/data/services/metabolomics/dev/studies/integrity-check-files
        readonly_storage_recycle_bin_root_path: /path/to/data/services/metabolomics/dev/studies/deleted-files
        rw_storage_recycle_bin_root_path: /path/to/data/rw/metabolomics/dev/studies/maintenance_test/deleted-files
        reports_root_path: /path/to/data/rw/metabolomics/dev/reports
        compounds_root_path: /file/path/to/compounds
        private_ftp_root_path: ""
        private_ftp_recycle_bin_root_path:  ""
        public_ftp_root_path: ""
        public_ftp_recycle_bin_root_path: ""

    private_ftp_user_home_path: ""
    max_study_in_submitted_status: 2
    min_study_creation_interval_in_mins: 5 
    audit_files_symbolic_link_name: AUDIT_FILES
    internal_files_symbolic_link_name: INTERNAL_FILES
    readonly_files_symbolic_link_name: FILES
    audit_folder_name: audit
    chebi_annotation_sub_folder: chebi_pipeline_annotations
    metadata_summary_file_name: metadata_summary.tsv
    data_files_summary_file_name: data_files_summary.tsv
    study_folder_maintenance_log_file_name: maintenance_log.tsv
    metadata_files_signature_file_name: metadata_files_signature.txt
    data_files_maintenance_file_name: data_files_summary.txt
    template_sample_file_name: s_Sample.txt
    files_list_json_file_name: files-all.json
    files_list_json_file_creation_timeout: 90
    investigation_file_name: i_Investigation.txt
    internal_logs_folder_name: logs
    internal_backup_folder_name: internal-backup
    validation_report_file_name: validation_report.json
    validation_files_json_name: validation_files.json
    validation_files_limit: 10000
    validation_script:/file/path/scripts/cluster_scripts/val/validation.sh
    missing_files_name: missing_files.txt

file_resources:
    mtbls_ontology_file: ./resources/Metabolights.owl
    mtbls_zooma_file: ./resources/metabolights_zooma.tsv
    mzml_xsd_schema_file_path: ./resources/mzML1.1.1_idx.xsd
    validations_file: ./resources/validation_schema.json
    study_default_template_path: ./resources/templates/study/default
    study_partner_metabolon_template_path: ./resources/templates/study/metabolon
    study_mass_spectrometry_maf_file_template_path: ./resources/m_metabolite_profiling_mass_spectrometry_v2_maf.tsv
    study_nmr_spectroscopy_maf_file_template_path: ./resources/m_metabolite_profiling_NMR_spectroscopy_v2_maf.tsv

file_filters:
    deleted_samples_prefix_tag: __TO_BE_DELETED__
    compressed_files_list:
    - .7z
    - .arj
    - .bz2
    - .cdf.gz
    - .g7z
    - .gz
    - .rar
    - .raw.rar
    - .tar
    - .war
    - .z
    - .zip
    - .zipx
    derived_data_folder_list:
    - chebi_pipeline_annotations
    derived_files_list:
    - .cdf
    - .cef
    - .cnx
    - .dx
    - .imzml
    - .mgf
    - .msp
    - .mzdata
    - .mzml
    - .mzxml
    - .nmrml
    - .peakml
    - .scan
    - .smp
    - .wiff
    - .xlsx
    - .xml
    - .xy
    - .mzxml
    empty_exclusion_list:
    - _chroms.inf
    - format.temp
    - metexplore_mapping.json
    - msactualdefs.xml
    - msmasscal.bin
    - msprofile.bin
    - prosol_history
    - synchelper
    - tcc_1.xml
    - tempbase
    - title
    folder_exclusion_list:
    - .d
    - .raw
    - /audit
    - /backup
    - /chebi
    - /chebi_pipeline_annotations
    - /metaspace
    - /old
    - audit
    - backup
    - chebi
    - chebi_pipeline_annotations
    - metaspace
    - old
    ignore_file_list:
    - _chroms
    - _extern
    - _func
    - _header
    - _history
    - _inlet
    - acqmethod
    - base_info
    - binpump
    - checksum.xml
    - clevels
    - defaultmasscal
    - devices.xml
    - format.temp
    - fq1list
    - gpnam
    - info.xml
    - isopump
    - metexplore_mapping
    - msactualdefs
    - msmasscal
    - msperiodicactuals
    - msprofile
    - msts.xml
    - outd
    - output
    - pdata
    - precom
    - prosol_history
    - pulseprogram
    - scon2
    - settings
    - shimvalues
    - specpar
    - stanprogram
    - synchelper
    - tcc_1
    - tdaspec
    - tempbase
    - title
    - tofdataindex
    - uxnmr
    - validation_files
    internal_mapping_list:
    - audit/logs
    - files-all
    - metexplore_mapping
    raw_files_list:
    - .abf
    - .cdf
    - .cdf.cmp
    - .cmp
    - .d
    - .dat
    - .hr
    - .ibd
    - .jpf
    - .lcd
    - .mgf
    - .qgd
    - .raw
    - .scan
    - .wiff
    - .xps
    rsync_exclude_list:
    - audit
    - files-all.json
    - metexplore_mapping.json
    - missing_files.txt
    - validation_files.json
    - validation_report.json
